### ISSUE TITLE
Feature - Add Image/bytes or IO support

### ISSUE THREAD

**Issue by jmillandev** [qTipTip/Pylette#19]
On my app I already have a image in memory. To use extract_colors I need to save it on a temp file, will be great if I can pass the bytes just.

Something like this:
```python
class ColorPaletteExtractor(Protocol):
    async def __call__(self, asset: bytes) -> List[str]:
        palette = extract_colors(asset, palette_size=10, resize=True)
        ...
```

**Comment by qTipTip** [comment]
Great suggestion! 

I'll try to get this implemented!

**Comment by qTipTip** [comment]
Can you look at #28 and tell me what you think? You can pass your bytes in the `image_bytes`-argument.
