### ISSUE TITLE
Dark/Light color theme extraction?

### ISSUE THREAD

**Issue by WantToLearnJapanese** [qTipTip/Pylette#25]
The library extracts a palette that does not consider light or dark themes.
Is there any recommended way to extract a light- or dark-themed palette?
Thanks

**Comment by qTipTip** [comment]
Hello! 👋 

As of now, no - this is something I haven't considered! However, if I find the time I'll look into it!

Thanks for the suggestion!

**Comment by qTipTip** [comment]
Hello again! 

I've decided that the process of theme generation is slightly out of scope of this library.
However, maybe you can have a look at how [colorgen](https://github.com/straightchlorine/colorgen) is doing it. It uses Pylette behind the scenes! 

All the best!
