### ISSUE TITLE
CLI Tool does not respect the `colorspace` argument and defaults to RGB

### ISSUE THREAD

**Issue by pranavAbe** [qTipTip/Pylette#40]
I'm using the CLI tool and specifying the `--colorspace` argument as `hsv` or `hls` does nothing as it generates the same set of palette values in RGB format. I'm also attaching an image below to demonstrate the issue. 

![image](https://github.com/user-attachments/assets/4bab4093-b5a8-4697-9d25-4534e33a5eac)

**Comment by qTipTip** [comment]
Hey! Thanks for reporting this! I'll look into this! This week, if I can find the time!

**Comment by qTipTip** [comment]
Hey, @pranavAbe ! I've released version 3.0.2, which should resolve this issue! Thanks for letting me know! 🚀
