### ISSUE TITLE
Pylette wants to install outside of target directory.  same file (aux.py) wont install with git.

### ISSUE THREAD

**Issue by chrisrogers3d** [qTipTip/Pylette#5]
ERROR: For req: Pylette. The wheel 'C:\\cygwin64\\tmp\\pip-unpack-m_zk5hpj\\Pyle
tte-0.4-py3-none-any.whl' has a file 'c:\\python39\\Lib\\site-packages\\Pylette\
\aux.py' trying to install outside the target directory 'c:\\python39\\Lib\\site
-packages'

$ git restore --source=HEAD :/
error: invalid path 'Pylette/aux.py'

**Comment by Nafeij** [comment]
@qTipTip
@chrisrogers3d Are you using Windows? I'm pretty sure it's related to [reserved filenames](NeuralEnsemble/PyNN#678).

**Comment by qTipTip** [comment]
Hey! @chrisrogers3d and @Nafeij ! Sorry for not seeing this before now. Thanks for letting me know! I'll try to get various things fixed within the next few weeks.

**Comment by qTipTip** [comment]
This should be solved here: https://github.com/qTipTip/Pylette/pull/11

Let me know if you have any additional issues! :)
